/**
 * SIMDM_MASTER_WSDL.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package localhost.EDMWS.earlybinding.options_2097152.DataRepository.SimDM_Master.QEX.SIMDM_MASTER_WSDL;

public interface SIMDM_MASTER_WSDL extends java.rmi.Remote {
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_blob_size_test[] test_blob_size(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean test_mapping(java.lang.String EDMsessionId, java.lang.String SOURCE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_item[] test_pbs_assignments_select(java.lang.String EDMsessionId, long ITEM1, long ITEM2, long DOMAIN, java.lang.String DOMAIN_TYPE1, java.lang.String DOMAIN_TYPE2, boolean LATEST_VERSION, java.lang.String BEFORE, java.lang.String AFTER, long CREATOR1, long CREATOR2, long PAGE, long START_FROM) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs_item[] test_pbs_search(java.lang.String EDMsessionId, java.lang.String PATTERN, long DOMAIN, java.lang.String DOMAIN_TYPE1, java.lang.String DOMAIN_TYPE2, java.lang.String TYPE1, java.lang.String TYPE2, java.lang.String ROLE1, java.lang.String ROLE2, boolean CASE_SENSITIVE, boolean EXACT_MATCH, boolean LATEST_VERSION, java.lang.String BEFORE, java.lang.String AFTER, long CREATOR1, long CREATOR2, long PAGE, long START_FROM) throws java.rmi.RemoteException;
    public java.lang.String test__echo(java.lang.String EDMsessionId, java.lang.String TEXT, long DELAY_IN_SECONDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_node_in_tree stm_test_import_file_system(java.lang.String EDMsessionId, long PARENT, java.lang.String COMMENT, java.lang.String NODE_TYPE, java.lang.String FILE_TYPE, boolean UPLOAD, java.lang.String i1, java.lang.String i2, java.lang.String i3, java.lang.String i4, java.lang.String i5, java.lang.String i6) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_node_in_tree stm_import_file_system(java.lang.String EDMsessionId, long PARENT, java.lang.String COMMENT, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_file_system_item[] ITEMS, java.lang.String NODE_TYPE, java.lang.String FILE_TYPE, boolean UPLOAD) throws java.rmi.RemoteException;
    public java.lang.String[] stm_list_node_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_instance_wrapper[] stm_file_delete(java.lang.String EDMsessionId, long FILE, long NODE, java.lang.String COMMENT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_instance_wrapper[] stm_node_delete(java.lang.String EDMsessionId, long SUBJECT, long PARENT, java.lang.String COMMENT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_remark[] stm_get_latest_remarks(java.lang.String EDMsessionId, java.lang.String AFTER, long PAGE_SIZE, long PAGE) throws java.rmi.RemoteException;
    public boolean stm_withdraw_resolution(java.lang.String EDMsessionId, long RESOLUTION) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_resolution stm_node_add_resolution(java.lang.String EDMsessionId, long NODE, java.lang.String RESOLUTION, java.lang.String REMARK) throws java.rmi.RemoteException;
    public java.lang.String[] stm_list_resolutions_awalable_for_me(java.lang.String EDMsessionId, long NODE_ID) throws java.rmi.RemoteException;
    public java.lang.String[] stm_list_awalable_resolutions(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean stm_withdraw_remark(java.lang.String EDMsessionId, long REMARK) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_remark stm_add_remark(java.lang.String EDMsessionId, long ITEM, java.lang.String SUBJ, java.lang.String REMARK) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_file[] stm_node_get_files(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_resolution[] stm_node_get_resolutions(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_remark[] stm_node_get_remarks(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_property[] stm_node_get_properties(java.lang.String EDMsessionId, long n) throws java.rmi.RemoteException;
    public java.lang.String stm_file_extract(java.lang.String EDMsessionId, long FILE, java.lang.String LINK) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_file stm_node_assign_file(java.lang.String EDMsessionId, long NODE, java.lang.String NAME, java.lang.String FILE_TYPE, java.lang.String LINK, java.lang.String DESCRIPTION, long SIZE, boolean UPLOAD) throws java.rmi.RemoteException;
    public java.lang.String[] stm_list_file_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_node_representation stm_node_get_representation(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_node_in_tree stm_node_get_file_system(java.lang.String EDMsessionId, long ID, long DEPTH) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_node_in_tree[] stm_open_node(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Stm_node_in_tree[] stm_node_get_children(java.lang.String EDMsessionId, long ID, java.lang.String TAGS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file model_file_create(java.lang.String EDMsessionId, long MODEL_ID, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file model_file_body_set(java.lang.String EDMsessionId, long ID, long SIZE, java.lang.String FILE_UPLOAD) throws java.rmi.RemoteException;
    public long model_file_body_get(java.lang.String EDMsessionId, long ID, java.lang.String DOWNLOADING_FILE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file model_attached_file_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs_item[] model_pbs_search(java.lang.String EDMsessionId, long MODEL_ID, java.lang.String PATTERN, java.lang.String[] ROLES, boolean CASE_SENSITIVE, boolean EXACT_MATCH, long DOMAIN, java.lang.String[] DOMAINS, boolean LATEST_VERSION, java.lang.String BEFORE, java.lang.String AFTER, long[] CREATORS, java.lang.String[] TYPES, long PAGE, long START_FROM) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Db_object[] node_file_list(java.lang.String EDMsessionId, long NODE_ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Db_object[] inner_model_node_list(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Db_object[] model_node_list(java.lang.String EDMsessionId, long MODEL_ID) throws java.rmi.RemoteException;
    public java.lang.String inner_property_value_set(java.lang.String EDMsessionId, long NODE_ID, java.lang.String PROPERTY_NAME, java.lang.String PROPERTY_VALUE) throws java.rmi.RemoteException;
    public java.lang.String model_property_value_set(java.lang.String EDMsessionId, long MODEL_ID, long NODE_ID, java.lang.String PROPERTY_NAME, java.lang.String PROPERTY_VALUE) throws java.rmi.RemoteException;
    public java.lang.String inner_model_property_create(java.lang.String EDMsessionId, java.lang.String PROPERTY_TYPE, java.lang.String PROPERTY_NAME, java.lang.String APPLICABLE_TO) throws java.rmi.RemoteException;
    public java.lang.String model_property_create(java.lang.String EDMsessionId, long MODEL_ID, java.lang.String PROPERTY_TYPE, java.lang.String PROPERTY_NAME, java.lang.String APPLICABLE_TO) throws java.rmi.RemoteException;
    public boolean node_patch_id(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean link_delete(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link link_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link[] link_select(java.lang.String EDMsessionId, long NODE, long FILE, long CREATOR, java.lang.String FILE_TYPE, java.lang.String LINK_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link[] link_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link link_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link link_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] link_list_types(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public boolean task_delete(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task task_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task[] task_select(java.lang.String EDMsessionId, long NODE, long PERSON, long METHOD, long APPROVAL, long CREATOR, java.lang.String TO_START_LESS, java.lang.String TO_START_GREATER, java.lang.String TO_FINISH_LESS, java.lang.String TO_FINISH_GREATER, java.lang.String APPROVAL_TYPE, java.lang.String METHOD_TYPE, java.lang.String TASK_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task[] task_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task task_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task task_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] task_list_types(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public boolean attached_file_delete(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file attached_file_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file[] attached_file_select(java.lang.String EDMsessionId, long NODE, long CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String ATTACHED_FILE_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file[] attached_file_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file attached_file_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file attached_file_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] attached_file_list_types(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property assigned_property_delete(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property assigned_property_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property[] assigned_property_select(java.lang.String EDMsessionId, long NODE, long PROPERTY, long CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String PROPERTY_TYPE, java.lang.String ASSIGNMENT_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property[] assigned_property_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property assigned_property_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property assigned_property_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] assigned_property_list_types(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public boolean assigned_person_delete(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person assigned_person_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person[] assigned_person_select(java.lang.String EDMsessionId, long NODE, long PERSON, long CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String PERSON_TYPE, java.lang.String ASSIGNMENT_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person[] assigned_person_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person assigned_person_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person assigned_person_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] assigned_person_list_types(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public boolean assigned_organization_delete(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization assigned_organization_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization[] assigned_organization_select(java.lang.String EDMsessionId, long NODE, long ORGANIZATION, long CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String ORGANIZATION_TYPE, java.lang.String ASSIGNMENT_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization[] assigned_organization_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization assigned_organization_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization assigned_organization_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] assigned_organization_list_types(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public boolean assigned_approval_delete(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval assigned_approval_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval[] assigned_approval_select(java.lang.String EDMsessionId, long NODE, long TASK, long APPROVAL, long CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String APPROVAL_TYPE, java.lang.String ASSIGNMENT_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval[] assigned_approval_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval assigned_approval_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval assigned_approval_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] assigned_approval_list_types(java.lang.String EDMsessionId, long ID, java.lang.String MS_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Merge_result node_merge(java.lang.String EDMsessionId, long TARGET_NODE_ID, java.lang.String SOURCE_MODEL, long SOURCE_ITEM_ID, java.lang.String USER_COMMENT, java.lang.String FORK_DATE) throws java.rmi.RemoteException;
    public long node_delete_version(java.lang.String EDMsessionId, long SUBJECT, java.lang.String SUBSTITUTE, boolean REMOVE_ALL_VERSIONS) throws java.rmi.RemoteException;
    public java.lang.String node_get_my_access(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_clone_branch(java.lang.String EDMsessionId, long SOURCE, long[] PARENTS, boolean SCELETON_ONLY) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_move(java.lang.String EDMsessionId, long ID, long[] OLD_PARENTS, long[] NEW_PARENTS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property[] node_get_properties(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person[] node_get_owning_persons(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization[] node_get_owning_organizations(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Info_line[] node_info(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node SUBJ) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Extract_result node_extract_ext(java.lang.String EDMsessionId, long ID, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public java.lang.String node_extract(java.lang.String EDMsessionId, long ID, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node[] node_branch_extend(java.lang.String EDMsessionId, long NODE_ID, long[] BRANCH, boolean INHERIT_CHILDREN, boolean INHERIT_FILES) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_shift_version(java.lang.String EDMsessionId, long[] REPLACE_IN, long[] ADD_TO, long NODE_ID, java.lang.String VERSION_TAG) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_create_successor(java.lang.String EDMsessionId, long ID, java.lang.String NEW_VERSION, long[] REMOVE_OLD_FORM, long[] ADD_NEW_TO, boolean INHERIT_CHILDREN, boolean INHERIT_FILES) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node[] node_get_children(java.lang.String EDMsessionId, long ID, java.lang.String VERSION) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node[] node_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.T_nodus node_get_whole_branch(java.lang.String EDMsessionId, long ID, java.lang.String VERSION) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_get(java.lang.String EDMsessionId, long ID, java.lang.String VERSION) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node SUBJECT, long[] IN_DOMAIN_OF_NODES) throws java.rmi.RemoteException;
    public java.lang.String[] node_list_types(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public java.lang.String item_get_timestamp(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public boolean item_insure_actual(java.lang.String EDMsessionId, long ID, java.lang.String CLIENT_TIMESTAMP) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Attached_file_validation_line[] collection_check_validations(java.lang.String EDMsessionId, long ID, boolean RETURN_ALL, boolean NOT_VALIDATED_ONLY) throws java.rmi.RemoteException;
    public boolean collection_set_editable(java.lang.String EDMsessionId, long ID, boolean FLAG) throws java.rmi.RemoteException;
    public boolean nodus_set_finalization(java.lang.String EDMsessionId, long ID, boolean FLAG) throws java.rmi.RemoteException;
    public java.lang.String file_import(java.lang.String EDMsessionId, java.lang.String SOURCE_MODEL, java.lang.String DOWNLOADING_FILE) throws java.rmi.RemoteException;
    public java.lang.String[] file_get_derived_models(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public long file_get_validation_log(java.lang.String EDMsessionId, long ID, java.lang.String LOG_FILE) throws java.rmi.RemoteException;
    public long file_CAX_set(java.lang.String EDMsessionId, long ID, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file CAX_FILE) throws java.rmi.RemoteException;
    public long file_body_get(java.lang.String EDMsessionId, long ID, java.lang.String DOWNLOADING_FILE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Validation_line[] file_list_validate(java.lang.String EDMsessionId, long[] IDS, long OPTIONS, java.lang.String LOG_FILE, boolean STORE_RESULT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Validation_line file_validate(java.lang.String EDMsessionId, long ID, long OPTIONS, java.lang.String LOG_FILE, boolean STORE_RESULT) throws java.rmi.RemoteException;
    public long file_CAX_generate(java.lang.String EDMsessionId, long ID, java.lang.String SRC_FILE, java.lang.String RESULT_FILE, java.lang.String LOG_FILE, boolean STORE_RESULT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_import_STEP(java.lang.String EDMsessionId, long ID, java.lang.String MODEL_NAME, java.lang.String FILE_UPLOAD, java.lang.String IMPORT_LOG) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_body_set(java.lang.String EDMsessionId, long ID, long SIZE, java.lang.String FILE_UPLOAD) throws java.rmi.RemoteException;
    public boolean file_cancel(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file[] file_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] file_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean comment_remove(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment comment_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment[] comment_select(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Specified_master_item SUBJ, long AUTHOR, java.lang.String AFTER, java.lang.String BEFORE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment[] comment_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment comment_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment comment(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] comment_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean method_cancel(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method method_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method[] method_select(java.lang.String EDMsessionId, long PBS, long CREATOR, java.lang.String VERSION, java.lang.String KIND) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method[] method_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method method_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method method_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] method_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean property_cancel(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property property_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property[] property_select(java.lang.String EDMsessionId, long PBS, long CREATOR, java.lang.String VERSION, java.lang.String KIND, java.lang.String APPLICABLE_TO) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property[] property_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property property_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property property_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] property_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean approval_cancel(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval approval_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval[] approval_select(java.lang.String EDMsessionId, long PBS, long CREATOR, java.lang.String VERSION, java.lang.String KIND) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval[] approval_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval approval_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval approval_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] approval_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_remove_person(java.lang.String EDMsessionId, long ID, long PERSON) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_add_person(java.lang.String EDMsessionId, long ID, long PERSON) throws java.rmi.RemoteException;
    public boolean organization_cancel(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization[] organization_select(java.lang.String EDMsessionId, long PBS, long PERSON, java.lang.String VERSION, java.lang.String ROLE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization[] organization_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] organization_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean person_cancel(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person[] person_select(java.lang.String EDMsessionId, long PBS, long ORGANIZATION, java.lang.String VERSION, java.lang.String ROLE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_get_me(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_get_by_login(java.lang.String EDMsessionId, java.lang.String ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person[] person_list(java.lang.String EDMsessionId, long[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_create_by_login(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] person_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Extract_result baseline_extract_ext(java.lang.String EDMsessionId, long ID, java.lang.String LOG_HEADER, boolean WITH_HISTORY, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public java.lang.String baseline_extract(java.lang.String EDMsessionId, long ID, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public boolean baseline_cancel(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline baseline_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline[] baseline_list(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline baseline_get(java.lang.String EDMsessionId, long ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline baseline_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] baseline_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public java.lang.String pbs_get_my_access(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_item[] pbs_assignments_select(java.lang.String EDMsessionId, long[] PBS_ITEMS, long DOMAIN, java.lang.String[] DOMAINS, boolean LATEST_VERSION, java.lang.String BEFORE, java.lang.String AFTER, long[] CREATORS, long PAGE, long START_FROM) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs_item[] pbs_search(java.lang.String EDMsessionId, java.lang.String PATTERN, java.lang.String[] ROLES, boolean CASE_SENSITIVE, boolean EXACT_MATCH, long DOMAIN, java.lang.String[] DOMAINS, boolean LATEST_VERSION, java.lang.String BEFORE, java.lang.String AFTER, long[] CREATORS, java.lang.String[] TYPES, long PAGE, long START_FROM) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment pbs_merge(java.lang.String EDMsessionId, java.lang.String SOURCE_MODEL, long SOURCE_ITEM_ID, java.lang.String TARGET_VERSION, java.lang.String USER_COMMENT, java.lang.String FORK_DATE) throws java.rmi.RemoteException;
    public java.lang.String[] pbs_get_edm_users(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public java.lang.String[] pbs_check(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Info_line[] pbs_info(java.lang.String EDMsessionId, java.lang.String VERSION, boolean CURRENT_ONLY) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs pbs_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String pbs_export(java.lang.String EDMsessionId, java.lang.String SOURCE_MODEL, java.lang.String DOWNLOADING_FILE, java.lang.String CONVERTOR_LOG) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Extract_result pbs_extract_ext(java.lang.String EDMsessionId, java.lang.String VERSION, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public java.lang.String pbs_extract(java.lang.String EDMsessionId, java.lang.String VERSION, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs pbs_fix_version(java.lang.String EDMsessionId, java.lang.String VERSION, boolean CREATE_CURRENT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.T_nodus pbs_get_whole_tree(java.lang.String EDMsessionId, java.lang.String VERSION) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs pbs_get(java.lang.String EDMsessionId, java.lang.String VERSION) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs pbs_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] pbs_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public java.lang.String[] system_login_list(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean system_cancel_login(java.lang.String EDMsessionId, java.lang.String LOGIN) throws java.rmi.RemoteException;
    public boolean system_change_password(java.lang.String EDMsessionId, java.lang.String LOGIN, java.lang.String PASSWORD) throws java.rmi.RemoteException;
    public boolean system_login_register(java.lang.String EDMsessionId, java.lang.String LOGIN) throws java.rmi.RemoteException;
    public java.lang.String[] system_get_models_of_schema(java.lang.String EDMsessionId, java.lang.String SCHEMA_NAME_PATTERN, java.lang.String REPOSITORY_NAME) throws java.rmi.RemoteException;
    public java.lang.String[] system_get_repositories_of_schema(java.lang.String EDMsessionId, java.lang.String SCHEMA_NAME_PATTERN) throws java.rmi.RemoteException;
    public java.lang.String system_text_error(java.lang.String EDMsessionId, long ERROR) throws java.rmi.RemoteException;
    public java.lang.String system_get_version(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public long fix_extension(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public java.lang.String _login(java.lang.String USER, java.lang.String GROUP, java.lang.String PASSWORD) throws java.rmi.RemoteException;
    public java.lang.String _logout(java.lang.String EDMSESSIONID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.FileTransferInfo _createTemporaryFile(java.lang.String EDMSESSIONID, java.lang.String FILENAME, java.lang.String FILETYPE, boolean UPLOAD) throws java.rmi.RemoteException;
    public java.lang.String _deleteTemporaryFile(java.lang.String EDMSESSIONID, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.FileTransferInfo FILEINFO) throws java.rmi.RemoteException;
    public java.lang.String _version(java.lang.String EDMSESSIONID) throws java.rmi.RemoteException;
}
