/**
 * SIMDM_MASTER_WSDL.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package localhost.EDMWS.earlybinding.options_2097152.DataRepository.SimDM_Master.QEX.SIMDM_MASTER_WSDL;

public interface SIMDM_MASTER_WSDL extends java.rmi.Remote {
    public java.lang.String test_on_error_do(java.lang.String EDMsessionId, int i) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_item[] test_pbs_assignments_select(java.lang.String EDMsessionId, int ITEM1, int ITEM2, int DOMAIN, java.lang.String DOMAIN_TYPE1, java.lang.String DOMAIN_TYPE2, boolean LATEST_VERSION, java.lang.String BEFORE, java.lang.String AFTER, int CREATOR1, int CREATOR2, int PAGE, int START_FROM) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs_item[] test_pbs_search(java.lang.String EDMsessionId, java.lang.String PATTERN, int DOMAIN, java.lang.String DOMAIN_TYPE1, java.lang.String DOMAIN_TYPE2, java.lang.String TYPE1, java.lang.String TYPE2, java.lang.String ROLE1, java.lang.String ROLE2, boolean CASE_SENSITIVE, boolean EXACT_MATCH, boolean LATEST_VERSION, java.lang.String BEFORE, java.lang.String AFTER, int CREATOR1, int CREATOR2, int PAGE, int START_FROM) throws java.rmi.RemoteException;
    public boolean node_patch_id(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean link_delete(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link link_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link[] link_select(java.lang.String EDMsessionId, int NODE, int FILE, int CREATOR, java.lang.String FILE_TYPE, java.lang.String LINK_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link[] link_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link link_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link link_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_link SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] link_list_types(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public boolean task_delete(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task task_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task[] task_select(java.lang.String EDMsessionId, int NODE, int PERSON, int METHOD, int APPROVAL, int CREATOR, java.lang.String TO_START_LESS, java.lang.String TO_START_GREATER, java.lang.String TO_FINISH_LESS, java.lang.String TO_FINISH_GREATER, java.lang.String APPROVAL_TYPE, java.lang.String METHOD_TYPE, java.lang.String TASK_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task[] task_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task task_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task task_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_task SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] task_list_types(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public boolean attached_file_delete(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file attached_file_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file[] attached_file_select(java.lang.String EDMsessionId, int NODE, int CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String ATTACHED_FILE_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file[] attached_file_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file attached_file_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file attached_file_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_attached_file SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] attached_file_list_types(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property assigned_property_delete(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property assigned_property_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property[] assigned_property_select(java.lang.String EDMsessionId, int NODE, int PROPERTY, int CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String PROPERTY_TYPE, java.lang.String ASSIGNMENT_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property[] assigned_property_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property assigned_property_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property assigned_property_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] assigned_property_list_types(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public boolean assigned_person_delete(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person assigned_person_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person[] assigned_person_select(java.lang.String EDMsessionId, int NODE, int PERSON, int CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String PERSON_TYPE, java.lang.String ASSIGNMENT_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person[] assigned_person_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person assigned_person_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person assigned_person_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] assigned_person_list_types(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public boolean assigned_organization_delete(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization assigned_organization_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization[] assigned_organization_select(java.lang.String EDMsessionId, int NODE, int ORGANIZATION, int CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String ORGANIZATION_TYPE, java.lang.String ASSIGNMENT_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization[] assigned_organization_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization assigned_organization_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization assigned_organization_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] assigned_organization_list_types(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public boolean assigned_approval_delete(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval assigned_approval_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval[] assigned_approval_select(java.lang.String EDMsessionId, int NODE, int TASK, int APPROVAL, int CREATOR, java.lang.String BEFORE, java.lang.String AFTER, java.lang.String APPROVAL_TYPE, java.lang.String ASSIGNMENT_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval[] assigned_approval_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval assigned_approval_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval assigned_approval_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_approval SUBJ) throws java.rmi.RemoteException;
    public java.lang.String[] assigned_approval_list_types(java.lang.String EDMsessionId, int ID, java.lang.String MS_TYPE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Merge_result node_merge(java.lang.String EDMsessionId, int TARGET_NODE_ID, java.lang.String SOURCE_MODEL, int SOURCE_ITEM_ID, java.lang.String USER_COMMENT, java.lang.String FORK_DATE) throws java.rmi.RemoteException;
    public int node_delete_version(java.lang.String EDMsessionId, int SUBJECT, java.lang.String SUBSTITUTE, boolean REMOVE_ALL_VERSIONS) throws java.rmi.RemoteException;
    public java.lang.String node_get_my_access(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_clone_branch(java.lang.String EDMsessionId, int SOURCE, int[] PARENTS, boolean SCELETON_ONLY) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_move(java.lang.String EDMsessionId, int ID, int[] OLD_PARENTS, int[] NEW_PARENTS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_property[] node_get_properties(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_person[] node_get_owning_persons(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_organization[] node_get_owning_organizations(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Info_line[] node_info(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node SUBJ) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Extract_result node_extract_ext(java.lang.String EDMsessionId, int ID, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public java.lang.String node_extract(java.lang.String EDMsessionId, int ID, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node[] node_branch_extend(java.lang.String EDMsessionId, int NODE_ID, int[] BRANCH, boolean INHERIT_CHILDREN, boolean INHERIT_FILES) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_shift_version(java.lang.String EDMsessionId, int[] REPLACE_IN, int[] ADD_TO, int NODE_ID, java.lang.String VERSION_TAG) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_create_successor(java.lang.String EDMsessionId, int ID, java.lang.String NEW_VERSION, int[] REMOVE_OLD_FORM, int[] ADD_NEW_TO, boolean INHERIT_CHILDREN, boolean INHERIT_FILES) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node[] node_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_get(java.lang.String EDMsessionId, int ID, java.lang.String VERSION) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node node_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_node SUBJECT, int[] IN_DOMAIN_OF_NODES) throws java.rmi.RemoteException;
    public java.lang.String[] node_list_types(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public java.lang.String item_get_timestamp(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public boolean item_insure_actual(java.lang.String EDMsessionId, int ID, java.lang.String CLIENT_TIMESTAMP) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Attached_file_validation_line[] collection_check_validations(java.lang.String EDMsessionId, int ID, boolean RETURN_ALL, boolean NOT_VALIDATED_ONLY) throws java.rmi.RemoteException;
    public boolean collection_set_editable(java.lang.String EDMsessionId, int ID, boolean FLAG) throws java.rmi.RemoteException;
    public boolean nodus_set_finalization(java.lang.String EDMsessionId, int ID, boolean FLAG) throws java.rmi.RemoteException;
    public java.lang.String file_import(java.lang.String EDMsessionId, java.lang.String SOURCE_MODEL, java.lang.String DOWNLOADING_FILE) throws java.rmi.RemoteException;
    public java.lang.String[] file_get_derived_models(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public int file_get_validation_log(java.lang.String EDMsessionId, int ID, java.lang.String LOG_FILE) throws java.rmi.RemoteException;
    public int file_CAX_set(java.lang.String EDMsessionId, int ID, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file CAX_FILE) throws java.rmi.RemoteException;
    public int file_body_get(java.lang.String EDMsessionId, int ID, java.lang.String DOWNLOADING_FILE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Validation_line[] file_list_validate(java.lang.String EDMsessionId, int[] IDS, int OPTIONS, java.lang.String LOG_FILE, boolean STORE_RESULT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Validation_line file_validate(java.lang.String EDMsessionId, int ID, int OPTIONS, java.lang.String LOG_FILE, boolean STORE_RESULT) throws java.rmi.RemoteException;
    public int file_CAX_generate(java.lang.String EDMsessionId, int ID, java.lang.String SRC_FILE, java.lang.String RESULT_FILE, java.lang.String LOG_FILE, boolean STORE_RESULT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_import_STEP(java.lang.String EDMsessionId, int ID, java.lang.String MODEL_NAME, java.lang.String FILE_UPLOAD, java.lang.String IMPORT_LOG) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_body_set(java.lang.String EDMsessionId, int ID, int SIZE, java.lang.String FILE_UPLOAD) throws java.rmi.RemoteException;
    public boolean file_cancel(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file[] file_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file file_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_file SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] file_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean comment_remove(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment comment_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment[] comment_select(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Specified_master_item SUBJ, int AUTHOR, java.lang.String AFTER, java.lang.String BEFORE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment[] comment_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment comment_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment comment(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] comment_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean method_cancel(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method method_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method[] method_select(java.lang.String EDMsessionId, int PBS, int CREATOR, java.lang.String VERSION, java.lang.String KIND) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method[] method_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method method_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method method_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_method SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] method_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean property_cancel(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property property_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property[] property_select(java.lang.String EDMsessionId, int PBS, int CREATOR, java.lang.String VERSION, java.lang.String KIND, java.lang.String APPLICABLE_TO) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property[] property_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property property_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property property_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_property SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] property_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean approval_cancel(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval approval_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval[] approval_select(java.lang.String EDMsessionId, int PBS, int CREATOR, java.lang.String VERSION, java.lang.String KIND) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval[] approval_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval approval_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval approval_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_approval SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] approval_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_remove_person(java.lang.String EDMsessionId, int ID, int PERSON) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_add_person(java.lang.String EDMsessionId, int ID, int PERSON) throws java.rmi.RemoteException;
    public boolean organization_cancel(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization[] organization_select(java.lang.String EDMsessionId, int PBS, int PERSON, java.lang.String VERSION, java.lang.String ROLE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization[] organization_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization organization_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_organization SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] organization_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean person_cancel(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person[] person_select(java.lang.String EDMsessionId, int PBS, int ORGANIZATION, java.lang.String VERSION, java.lang.String ROLE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_get_me(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_get_by_login(java.lang.String EDMsessionId, java.lang.String ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person[] person_list(java.lang.String EDMsessionId, int[] IDS) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_create_by_login(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person person_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_person SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] person_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Extract_result baseline_extract_ext(java.lang.String EDMsessionId, int ID, java.lang.String LOG_HEADER, boolean WITH_HISTORY, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public java.lang.String baseline_extract(java.lang.String EDMsessionId, int ID, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public boolean baseline_cancel(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline baseline_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline SUBJECT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline[] baseline_list(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline baseline_get(java.lang.String EDMsessionId, int ID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline baseline_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_baseline SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] baseline_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public java.lang.String pbs_get_my_access(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_assigned_item[] pbs_assignments_select(java.lang.String EDMsessionId, int[] PBS_ITEMS, int DOMAIN, java.lang.String[] DOMAINS, boolean LATEST_VERSION, java.lang.String BEFORE, java.lang.String AFTER, int[] CREATORS, int PAGE, int START_FROM) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs_item[] pbs_search(java.lang.String EDMsessionId, java.lang.String PATTERN, java.lang.String[] ROLES, boolean CASE_SENSITIVE, boolean EXACT_MATCH, int DOMAIN, java.lang.String[] DOMAINS, boolean LATEST_VERSION, java.lang.String BEFORE, java.lang.String AFTER, int[] CREATORS, java.lang.String[] TYPES, int PAGE, int START_FROM) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_comment pbs_merge(java.lang.String EDMsessionId, java.lang.String SOURCE_MODEL, int SOURCE_ITEM_ID, java.lang.String TARGET_VERSION, java.lang.String USER_COMMENT, java.lang.String FORK_DATE) throws java.rmi.RemoteException;
    public java.lang.String[] pbs_get_edm_users(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public java.lang.String[] pbs_check(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Info_line[] pbs_info(java.lang.String EDMsessionId, java.lang.String VERSION, boolean CURRENT_ONLY) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs pbs_update(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String pbs_export(java.lang.String EDMsessionId, java.lang.String SOURCE_MODEL, java.lang.String DOWNLOADING_FILE, java.lang.String CONVERTOR_LOG) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.Extract_result pbs_extract_ext(java.lang.String EDMsessionId, java.lang.String VERSION, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public java.lang.String pbs_extract(java.lang.String EDMsessionId, java.lang.String VERSION, boolean WITH_HISTORY, java.lang.String USER_COMMENT, java.lang.String TARGET_MODEL, java.lang.String PDI_FILE) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs pbs_fix_version(java.lang.String EDMsessionId, java.lang.String VERSION, boolean CREATE_CURRENT) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs pbs_get(java.lang.String EDMsessionId, java.lang.String VERSION) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs pbs_create(java.lang.String EDMsessionId, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.V_pbs SUBJECT) throws java.rmi.RemoteException;
    public java.lang.String[] pbs_list_types(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public java.lang.String[] system_login_list(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public boolean system_cancel_login(java.lang.String EDMsessionId, java.lang.String LOGIN) throws java.rmi.RemoteException;
    public boolean system_change_password(java.lang.String EDMsessionId, java.lang.String LOGIN, java.lang.String PASSWORD) throws java.rmi.RemoteException;
    public boolean system_login_register(java.lang.String EDMsessionId, java.lang.String LOGIN) throws java.rmi.RemoteException;
    public java.lang.String[] system_get_models_of_schema(java.lang.String EDMsessionId, java.lang.String SCHEMA_NAME_PATTERN, java.lang.String REPOSITORY_NAME) throws java.rmi.RemoteException;
    public java.lang.String[] system_get_repositories_of_schema(java.lang.String EDMsessionId, java.lang.String SCHEMA_NAME_PATTERN) throws java.rmi.RemoteException;
    public java.lang.String system_get_version(java.lang.String EDMsessionId) throws java.rmi.RemoteException;
    public java.lang.String _login(java.lang.String USER, java.lang.String GROUP, java.lang.String PASSWORD) throws java.rmi.RemoteException;
    public java.lang.String _logout(java.lang.String EDMSESSIONID) throws java.rmi.RemoteException;
    public com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.FileTransferInfo _createTemporaryFile(java.lang.String EDMSESSIONID, java.lang.String FILENAME, java.lang.String FILETYPE, boolean UPLOAD) throws java.rmi.RemoteException;
    public java.lang.String _deleteTemporaryFile(java.lang.String EDMSESSIONID, com.jotne.epmtech.SIMDM_MASTER.SIMDM_MASTER_WSDL.FileTransferInfo FILEINFO) throws java.rmi.RemoteException;
    public java.lang.String _version(java.lang.String EDMSESSIONID) throws java.rmi.RemoteException;
}
